version: '3.8'

services:
  api:
    container_name: shotify_api
    build:
      dockerfile: shotify/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - selenium
      - minio
    networks:
      - shotify

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: screenshot_db
    ports:
      - "5432:5432"
    networks:
      - shotify

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - shotify

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    networks:
      - shotify

networks:
  shotify:
    driver: bridge
